In [1]:
import pandas as pd
import numpy

Q1

In [2]:
numpy.__version__

'1.22.4'

Q2

In [3]:
data = pd.read_csv('../data/data.csv')
data.shape

(11914, 16)

In [4]:
data.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

Q3

In [5]:
data.Make.value_counts().head(3)

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

Q4

In [6]:
len(data[data['Make']=='Audi']['Model'].value_counts().index)

34

Q5

In [7]:
sum(data.isna().sum() != 0 )

5

In [8]:
data.isna().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

Q6

In [9]:
data['Number of Doors'].median() == data['Number of Doors'].dropna().median()

True

In [10]:
data['Engine HP'].median() == data['Engine HP'].dropna().median()

True

In [11]:
data['Engine Cylinders'].median() == data['Engine Cylinders'].dropna().median()

True

Q7

In [12]:
X = data[data['Make']=='Lotus'][['Engine HP','Engine Cylinders']].drop_duplicates().to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [13]:
XT =  X.T
XT

array([[189., 218., 217., 350., 400., 276., 345., 257., 240.],
       [  4.,   4.,   4.,   8.,   6.,   6.,   6.,   4.,   4.]])

In [14]:
XTX = XT.dot(X)
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [15]:
XTX_inv = numpy.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [16]:
y= numpy.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [17]:
XTX_invXT = XTX_inv.dot(XT)
XTX_invXT

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [18]:
w = XTX_invXT.dot(y)
w

array([  4.59494481, -63.56432501])